spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=TriMiCinema;trustServerCertificate=true;
    username: sa
    password: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

jwt:
  signerKey: "Vz8SbmcFpTpK4iDX65I2q469YpxP1pizxOKcze/SH9g5J+HRuFjkbfcswze5nvdr"