spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=TriMiCinema;trustServerCertificate=true;
    username: sa
    password: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

  port: 8080

vnpay:
  tmnCode: IP21AIAL
  hashSecret: L44APGGLO7H328N20SFLRY1ROX4YBBUR
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:5173/bookingSuccess

jwt:
  signerKey: "Vz8SbmcFpTpK4iDX65I2q469YpxP1pizxOKcze/SH9g5J+HRuFjkbfcswze5nvdr"
